Repository ElektraInitiative/PermaplanT, pull requests merged in 2023-07, with the labels that each got.

#521 CI: mdbook added to pipeline + Build badge
  README.md
  ci/Jenkinsfile
  ci/Jenkinsfile.release
  doc/CHANGELOG.md
  frontend/.prettierignore
Labels: please review, CI

#537 Issue forms
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .gitignore
  doc/CHANGELOG.md
Labels: please review

#554 Fix broken links in mdbook
  doc/CHANGELOG.md
  doc/architecture/04solution.md
  doc/architecture/05building.md
  doc/architecture/10quality.md
  doc/architecture/12glossary.md
  doc/backend/01setup.md
  doc/database/hierarchy.md
  doc/decisions/database_plant_hierarchy.md
  doc/decisions/frontend_offloading.md
  doc/decisions/map_undo_redo_implementation.md
  doc/decisions/reversible_deletion.md
  doc/guidelines/documentation.md
  doc/meetings/2023_02_17.md
  doc/meetings/2023_04_04.md
  doc/meetings/2023_04_25.md
  doc/meetings/2023_05_02.md
  doc/meetings/2023_05_23.md
  doc/meetings/2023_05_30.md
  doc/meetings/2023_06_06.md
  doc/meetings/2023_06_13.md
  doc/meetings/2023_06_20.md
  doc/meetings/2023_06_27.md
  doc/usecases/assigned/buy_seeds.md
  doc/usecases/assigned/contributing_member.md
  doc/usecases/assigned/diversity_score.md
  doc/usecases/assigned/landing_page_news.md
  doc/usecases/assigned/map_collaboration.md
  doc/usecases/assigned/map_honors.md
  doc/usecases/assigned/plant_lore.md
  doc/usecases/assigned/review_plant_relationships.md
  doc/usecases/assigned/reward_preview.md
  doc/usecases/assigned/warnings_layer.md
  doc/usecases/current/area_of_plants.md
  doc/usecases/current/gain_blossoms.md
  doc/usecases/current/landing_page.md
  doc/usecases/current/photo_layer.md
  doc/usecases/current/plants_layer.md
  doc/usecases/current/search_plants.md
  doc/usecases/done/layers_visibility.md
  doc/usecases/draft/map_webcam.md
Labels: documentation, help wanted, please review

#552 Devcontainer support
  .devcontainer/.env
  .devcontainer/.env.backend
  .devcontainer/.env.frontend
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.pg
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/pgpass
  .devcontainer/servers.json
  .devcontainer/setup.sh
  README.md
  doc/CHANGELOG.md
Labels: CI

#515 Finish map creation use case
  backend/src/config/routes.rs
  backend/src/controller/map.rs
  backend/src/model/dto.rs
  backend/src/model/dto/update_map_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/map_impl.rs
  backend/src/model/enum/privacy_options.rs
  backend/src/service/map.rs
  backend/src/test/map.rs
  doc/usecases/done/map_creation.md
  frontend/src/config/i18n/de/common.json
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/de/maps.json
  frontend/src/config/i18n/de/privacyOptions.json
  frontend/src/config/i18n/en/common.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/config/i18n/en/maps.json
  frontend/src/config/i18n/en/privacyOptions.json
  frontend/src/features/maps/api/findMapById.ts
  frontend/src/features/maps/api/updateMap.ts
  frontend/src/features/maps/components/MapCard.tsx
  frontend/src/features/maps/index.ts
  frontend/src/features/maps/routes/MapCreateForm.tsx
  frontend/src/features/maps/routes/MapEditForm.tsx
  frontend/src/features/maps/routes/MapOverview.tsx
  frontend/src/icons/edit.svg
  frontend/src/routes/index.ts
  frontend/src/routes/types.ts
Labels: please review

#516 return version from config endpoint
  backend/src/controller/config.rs
  backend/src/model/dto.rs
Labels: please review

#557 CI: Cancel previous builds
  ci/Jenkinsfile
  doc/CHANGELOG.md
  doc/ci.md
Labels: enhancement, please review, please merge, CI

#576 Hover tooltips for MapCard buttons
  doc/CHANGELOG.md
  frontend/src/config/i18n/de/maps.json
  frontend/src/config/i18n/en/maps.json
  frontend/src/features/maps/components/MapCard.tsx
Labels: please review

#580 Bugfix/541 plant icons
  doc/CHANGELOG.md
  frontend/src/features/map_planning/components/BaseStage.tsx
Labels: please review

#579 Improved texts in map editor
  doc/CHANGELOG.md
  frontend/src/config/i18n/de/baseLayerForm.json
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/de/layers.json
  frontend/src/config/i18n/de/plantEdit.json
  frontend/src/config/i18n/de/plantSearch.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/config/i18n/en/layers.json
  frontend/src/config/i18n/en/plantEdit.json
  frontend/src/config/i18n/en/plantSearch.json
  frontend/src/features/map_planning/components/toolbar/LayerList.tsx
  frontend/src/features/map_planning/components/toolbar/Layers.tsx
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantLayerLeftToolbar.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantSearch.tsx
Labels: please review

#556 Send email when master fails
  ci/Jenkinsfile
  doc/CHANGELOG.md
  doc/tests/README.md
Labels: please review, CI

#549 Makefile
  Makefile
  README.md
  backend/Makefile
  backend/README.md
  doc/CHANGELOG.md
  doc/backend/01setup.md
Labels: CI

#599 151 frontend error handling
  doc/CHANGELOG.md
  frontend/src/App.tsx
  frontend/src/config/i18n/de/auth.json
  frontend/src/config/i18n/de/layers.json
  frontend/src/config/i18n/de/maps.json
  frontend/src/config/i18n/de/nextcloudIntegration.json
  frontend/src/config/i18n/de/plantEdit.json
  frontend/src/config/i18n/de/plantSearch.json
  frontend/src/config/i18n/de/plantingSuggestions.json
  frontend/src/config/i18n/de/seeds.json
  frontend/src/config/i18n/en/auth.json
  frontend/src/config/i18n/en/layers.json
  frontend/src/config/i18n/en/maps.json
  frontend/src/config/i18n/en/nextcloudIntegration.json
  frontend/src/config/i18n/en/plantEdit.json
  frontend/src/config/i18n/en/plantSearch.json
  frontend/src/config/i18n/en/plantingSuggestions.json
  frontend/src/config/i18n/en/seeds.json
  frontend/src/features/map_planning/layers/plant/hooks/useFindPlantById.ts
  frontend/src/features/map_planning/layers/plant/hooks/usePlantSearch.ts
  frontend/src/features/map_planning/layers/plant/hooks/useSeasonalAvailablePlants.ts
  frontend/src/features/map_planning/routes/MapWrapper.tsx
  frontend/src/features/maps/routes/MapCreateForm.tsx
  frontend/src/features/maps/routes/MapEditForm.tsx
  frontend/src/features/maps/routes/MapOverview.tsx
  frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts
  frontend/src/features/seeds/routes/CreateSeed.tsx
  frontend/src/features/seeds/routes/SeedDetails.tsx
  frontend/src/features/seeds/routes/ViewSeeds.tsx
  frontend/src/features/seeds/store/CreateSeedStore.ts
  frontend/src/hooks/useSafeAuth.tsx
Labels: please review

#574 Version number displayed on the navbar, moved github link to the footer
  doc/CHANGELOG.md
  frontend/src/Providers.tsx
  frontend/src/components/Layout/Footer.tsx
  frontend/src/components/Layout/Navbar.tsx
Labels: enhancement, frontend

#563 Devcontainer fix + improvements
  .devcontainer/.env
  .devcontainer/.env.backend
  .devcontainer/.env.db
  .devcontainer/.env.frontend
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/setup.sh
  README.md
  doc/CHANGELOG.md
  doc/development_setup.md
Labels: please merge

#604 CI: Mdbook link checker
  .github/PULL_REQUEST_TEMPLATE.md
  book.toml
  ci/container-images/permaplant-mdbook/Dockerfile
  doc/CHANGELOG.md
  doc/architecture/05building.md
  doc/architecture/10quality.md
  doc/database/hierarchy.md
  doc/decisions/reversible_deletion.md
  doc/guidelines/documentation.md
  doc/meetings/2023_07_04.md
  doc/research/nextcloud_integration.md
  doc/usecases/README.md
  doc/usecases/done/layers_visibility.md
Labels: please review, CI

#624 Fix broken links + add mdbook-linkcheck to make install, closes #558
  doc/development_setup.md
Labels: urgent, CI

#628 Enable warning-policy error in mdbook
  book.toml
  doc/architecture/03context.md
  doc/meetings/2022_12_16.md
  doc/meetings/2023_03_14.md
  doc/meetings/2023_03_21.md
  doc/meetings/2023_04_04.md
  doc/meetings/2023_04_11.md
  doc/research/nextcloud_integration.md
  doc/tests/protocols/README.md
  doc/tests/protocols/template.md
  doc/usecases/assigned/membership_application.md
Labels: documentation, please merge

#631 Add ram requirements to dev setup
  doc/development_setup.md
Labels: documentation

#629 Fix three vulnerabilities and broken link in pipeline
  doc/CHANGELOG.md
  doc/tests/protocols/plant_search.md
  frontend/package-lock.json
  frontend/package.json
Labels: please merge, frontend

#566 Backend heatmap
  backend/Cargo.lock
  backend/Cargo.toml
  backend/migrations/2023-07-03-165000_heatmap/down.sql
  backend/migrations/2023-07-03-165000_heatmap/up.sql
  backend/src/config/api_doc.rs
  backend/src/config/routes.rs
  backend/src/controller/plant_layer.rs
  backend/src/model/dto.rs
  backend/src/model/dto/map_impl.rs
  backend/src/model/dto/new_map_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/plant_layer.rs
  backend/src/schema.patch
  backend/src/service/plant_layer.rs
  backend/src/test/layers.rs
  backend/src/test/map.rs
  backend/src/test/mod.rs
  backend/src/test/plant_layer.rs
  backend/src/test/plant_layer_heatmap.rs
  backend/src/test/util.rs
  backend/src/test/util/data.rs
  backend/src/test/util/dummy_map_polygons.rs
  doc/CHANGELOG.md
  doc/architecture/04solution.md
  doc/backend/05updating_schema_patch.md
  doc/tests/protocols/MTP_2023-07-8_Heatmap_V1.md
  frontend/src/features/maps/routes/MapCreateForm.tsx
  frontend/src/features/maps/routes/MapOverview.tsx
Labels: please review, please merge, backend

#642 Improve manual test case docu
  doc/CHANGELOG.md
  doc/tests/manual/README.md
  doc/tests/manual/protocol.md
  doc/tests/manual/reports/230715_EXAMPLE.md
  doc/tests/manual/reports/README.md
  doc/tests/protocols/README.md
  doc/tests/protocols/plant_search.md
  doc/tests/protocols/template.md
  doc/usecases/README.md
Labels: documentation, please merge

#651 Remove Heatmap test protocol temporary
  doc/tests/manual/protocol.md
  doc/tests/protocols/MTP_2023-07-8_Heatmap_V1.md
Labels: urgent, please merge

#595 Add cronjob for maps deletion
  backend/migrations/2023-07-11-095000_map_cascading_deletes/down.sql
  backend/migrations/2023-07-11-095000_map_cascading_deletes/up.sql
  backend/src/db/cronjobs.rs
  backend/src/db/mod.rs
  backend/src/main.rs
  doc/CHANGELOG.md
  doc/backend/05cronjobs.md
  doc/database/cronjobs.md
Labels: please merge, backend

#618 Fix a bug where the image error toast would show unexpectedly
  frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts
Labels: please review, urgent

#660 Lock mdbook summary version
  ci/container-images/permaplant-mdbook/Dockerfile
  doc/backend/README.md
Labels: urgent, CI

#652 Feature/547 timeline edit plantings dates in sidebar
  backend/src/controller/plantings.rs
  backend/src/model/dto/actions.rs
  backend/src/model/dto/plantings.rs
  backend/src/model/dto/plantings_impl.rs
  backend/src/model/entity/plantings.rs
  doc/CHANGELOG.md
  doc/tests/manual/protocol.md
  doc/tests/protocols/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button/SimpleButton.tsx
  frontend/src/components/Button/__snapshots__/SimpleButton.test.tsx.snap
  frontend/src/components/Form/SimpleFormInput.tsx
  frontend/src/components/Form/__snapshots__/SimpleFormInput.test.tsx.snap
  frontend/src/components/Modals/__snapshots__/SimpleModal.test.tsx.snap
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/de/plantEdit.json
  frontend/src/config/i18n/de/plantings.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/config/i18n/en/plantEdit.json
  frontend/src/config/i18n/en/plantings.json
  frontend/src/features/map_planning/api/getPlantings.ts
  frontend/src/features/map_planning/api/updateAddDatePlanting.ts
  frontend/src/features/map_planning/api/updateRemoveDatePlanting.ts
  frontend/src/features/map_planning/components/timeline/Timeline.tsx
  frontend/src/features/map_planning/layers/plant/actions.ts
  frontend/src/features/map_planning/layers/plant/components/EmptyList/EmptyAvailablePlants.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantLayerLeftToolbar.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
  frontend/src/features/map_planning/layers/plant/hooks/useFindPlantById.ts
  frontend/src/features/map_planning/store/RemoteActions.ts
  frontend/src/features/map_planning/store/UntrackedMapStore.ts
  frontend/src/features/nextcloud_integration/api/getImages.ts
  frontend/src/hooks/useDebouncedSubmit.tsx
  frontend/src/routes/Pages/Pages.tsx
  frontend/src/styles/globals.css
Labels: please review

#597 CI: Check package-lock.json after install
  ci/Jenkinsfile
  ci/container-images/permaplant-node/Dockerfile
  doc/CHANGELOG.md
  doc/development_setup.md
  frontend/README.md
Labels: CI

#577 CI: Parallelizing cargo build and test
  ci/Jenkinsfile
  ci/build-scripts/build-backend.sh
  ci/build-scripts/build-schema.sh
  doc/CHANGELOG.md
Labels: please merge, CI

#585 CI: Optimized mdbook docker image
  Makefile
  ci/Jenkinsfile
  ci/container-images/permaplant-mdbook/Dockerfile
  doc/CHANGELOG.md
  doc/Dockerfile
Labels: please review, CI

#685 Groovy linter/fixer/formatter added
  .pre-commit-config.yaml
  ci/Jenkinsfile
  ci/Jenkinsfile.release
  doc/CHANGELOG.md
Labels: CI

#596 CI: Test migrations
  backend/migrations/2023-07-01-152628_squashed_setup/down.sql
  ci/Jenkinsfile
  ci/container-images/permaplant-rust/Dockerfile
  doc/CHANGELOG.md
Labels: CI

#663 Heatmap documentation
  backend/src/controller/plant_layer.rs
Labels: documentation, please review

#688 CI: Move clippy, remove check
  ci/Jenkinsfile
  doc/CHANGELOG.md
Labels: CI

#704 move map geometry to own migration
  backend/migrations/2023-07-03-164000_add_map_geometry/down.sql
  backend/migrations/2023-07-03-164000_add_map_geometry/up.sql
  backend/migrations/2023-07-03-165000_heatmap/down.sql
  backend/migrations/2023-07-03-165000_heatmap/up.sql
  backend/src/test/mod.rs
Labels: please review, please merge, backend

#619 End-to-end testing decision
  doc/decisions/frontend_e2e_testing.md
  doc/tests/README.md
Labels: documentation, please merge, CI, frontend

#625 CI: Login/Logout e2e test
  .gitignore
  Makefile
  ci/Jenkinsfile
  ci/container-images/permaplant-e2e/Dockerfile
  doc/CHANGELOG.md
  e2e/.gitignore
  e2e/ReadMe.md
  e2e/__init__.py
  e2e/conftest.py
  e2e/features/login_logout.feature
  e2e/install.sh
  e2e/pages/__init__.py
  e2e/pages/abstract_page.py
  e2e/pages/home.py
  e2e/pages/login.py
  e2e/pytest.ini
  e2e/requirements.txt
  e2e/steps/__init__.py
  e2e/steps/test_login_logout.py
Labels: CI, frontend

#707 E2E: Map creation tests
  .gitignore
  Makefile
  ci/Jenkinsfile
  ci/Jenkinsfile.release
  doc/CHANGELOG.md
  doc/decisions/frontend_e2e_testing.md
  doc/tests/manual/protocol.md
  doc/tests/manual/reports/230725.md
  e2e/.gitignore
  e2e/Dockerfile
  e2e/ReadMe.md
  e2e/conftest.py
  e2e/features/map_creation.feature
  e2e/pages/abstract_page.py
  e2e/pages/home.py
  e2e/pages/login.py
  e2e/pages/maps/create.py
  e2e/pages/maps/edit.py
  e2e/pages/maps/management.py
  e2e/requirements.txt
  e2e/steps/test_login_logout.py
  e2e/steps/test_map_creation.py
  frontend/src/config/i18n/en/guidedTour.json
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
Labels: CI

#730 Improve Tour for release 0.3
  doc/tests/manual/protocol.md
  frontend/src/config/i18n/de/guidedTour.json
  frontend/src/config/i18n/en/guidedTour.json
  frontend/src/features/map_planning/components/Map.tsx
  frontend/src/features/map_planning/utils/EditorTour.ts
Labels: please review

#748 E2E: Fix failing map creation tests
  e2e/features/map_creation.feature
  e2e/pages/maps/create.py
  e2e/steps/test_map_creation.py
Labels: bug, CI

#749 CI: Wait for pr db before running e2e tests
  ci/Jenkinsfile
Labels: CI
