Repository ElektraInitiative/PermaplanT, pull requests merged in 2023-05, with the labels that each got.

#245 Add maps, users and blossoms DB schema and ER diagram
  doc/architecture/database_schemata.md
Labels: please review

#307 document backend architecture resolves #294 resolves #247
  .reuse/dep5
  README.md
  backend/src/main.rs
  book.toml
  ci/Jenkinsfile
  ci/container-images/permaplant-mdbook/Dockerfile
  doc/architecture/backend.md
  doc/architecture/glossary.md
  doc/contrib/frontend.md
  doc/database/README.md
  doc/development_setup.md
  doc/meetings/2023_03_21.md
  doc/meetings/2023_04_27_db.md
  doc/mermaid-init.js
  doc/mermaid.min.js
  doc/research/README.md
  doc/research/nextcloud_integration.md
  doc/tests/frontend.md
  doc/usecases/gamification/README.md
  doc/usecases/map_versioning.md
Labels: please review

#74 1 write nextcloud use cases
  doc/architecture/glossary.md
  doc/usecases/calendar.md
  doc/usecases/event_notfication.md
  doc/usecases/geo_map.md
  doc/usecases/landing_page.md
  doc/usecases/layers/map_webcam.md
  doc/usecases/layers/photo_layer.md
  doc/usecases/login.md
  doc/usecases/membership_application.md
  doc/usecases/new_member_notification.md
  doc/usecases/visitor_chat.md
Labels: please review, please merge

#244 Feature/189 toolbars for map planning
  frontend/custom.d.ts
  frontend/jest.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__mocks__/svg.ts
  frontend/src/components/Button/IconButton.tsx
  frontend/src/components/Form/SearchInput.tsx
  frontend/src/components/Form/__snapshots__/SearchInput.test.tsx.snap
  frontend/src/components/Layout/NavContainer.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Slider/NamedSlider.stories.tsx
  frontend/src/components/Slider/NamedSlider.tsx
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/de/layerSettings.json
  frontend/src/config/i18n/de/plantSearch.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/config/i18n/en/layerSettings.json
  frontend/src/config/i18n/en/plantSearch.json
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/components/toolbar/LayerSettings.stories.tsx
  frontend/src/features/map_planning/components/toolbar/LayerSettings.tsx
  frontend/src/features/map_planning/components/toolbar/Layers.stories.tsx
  frontend/src/features/map_planning/components/toolbar/Layers.tsx
  frontend/src/features/map_planning/components/toolbar/PlantSearch.stories.tsx
  frontend/src/features/map_planning/components/toolbar/PlantSearch.tsx
  frontend/src/features/map_planning/components/toolbar/Toolbar.stories.tsx
  frontend/src/features/map_planning/components/toolbar/Toolbar.tsx
  frontend/src/features/map_planning/layers/PlantsLayer.tsx
  frontend/src/features/map_planning/routes/Map.tsx
  frontend/src/icons/add.svg
  frontend/src/icons/arrow.svg
  frontend/src/icons/caret-down.svg
  frontend/src/icons/caret-right.svg
  frontend/src/icons/copy.svg
  frontend/src/icons/drag.svg
  frontend/src/icons/drag_filling.svg
  frontend/src/icons/eye-off.svg
  frontend/src/icons/eye.svg
  frontend/src/icons/move.svg
  frontend/src/icons/plant.svg
  frontend/src/icons/redo.svg
  frontend/src/icons/search.svg
  frontend/src/icons/trash.svg
  frontend/src/icons/undo.svg
  frontend/tsconfig.json
Labels: please review, please merge

#323 Map creation
  backend/migrations/2023-04-26-154153_map_creation/down.sql
  backend/migrations/2023-04-26-154153_map_creation/up.sql
  backend/migrations/2023-05-05-075334_map_versions/down.sql
  backend/migrations/2023-05-05-075334_map_versions/up.sql
  backend/migrations/2023-05-05-123527_map_owner/down.sql
  backend/migrations/2023-05-05-123527_map_owner/up.sql
  backend/src/config/routes.rs
  backend/src/controller/map.rs
  backend/src/controller/mod.rs
  backend/src/model/dto.rs
  backend/src/model/dto/map_impl.rs
  backend/src/model/dto/map_version_impl.rs
  backend/src/model/dto/new_map_impl.rs
  backend/src/model/dto/new_map_version_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/map_impl.rs
  backend/src/model/entity/map_version_impl.rs
  backend/src/service/map.rs
  backend/src/service/mod.rs
  backend/src/test/map.rs
  backend/src/test/mod.rs
  frontend/src/assets/heart.svg
  frontend/src/assets/heart_dark.svg
  frontend/src/assets/person.svg
  frontend/src/assets/person_dark.svg
  frontend/src/components/Card/InfoMessage.tsx
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/de/maps.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/config/i18n/en/maps.json
  frontend/src/features/maps/api/createMap.ts
  frontend/src/features/maps/api/findAllMaps.ts
  frontend/src/features/maps/components/CountingButton.tsx
  frontend/src/features/maps/components/MapCard.tsx
  frontend/src/features/maps/components/MapCreateModal.tsx
  frontend/src/features/maps/index.ts
  frontend/src/features/maps/routes/MapOverview.tsx
  frontend/src/routes/index.ts
  frontend/src/routes/types.ts
Labels: please review

#162 gamification use cases
  doc/usecases/gamification/ingredient_lists.md
  doc/usecases/gamification/map_collaboration.md
Labels: please review

#308 Feature/undo redo
  frontend/__mocks__/zustand.ts
  frontend/jest.config.ts
  frontend/jest.setup.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Button/__snapshots__/ButtonLink.test.tsx.snap
  frontend/src/components/Form/CreatableSelectMenu.test.tsx
  frontend/src/components/Form/PaginatedSelectMenu.test.tsx
  frontend/src/components/Form/SearchInput.test.tsx
  frontend/src/components/Form/SelectMenu.test.tsx
  frontend/src/config/__mocks__/env.ts
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/de/undoRedo.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/config/i18n/en/undoRedo.json
  frontend/src/config/i18n/index.ts
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/routes/Map.tsx
  frontend/src/features/undo_redo/index.ts
  frontend/src/features/undo_redo/store/MapHistoryStore.test.ts
  frontend/src/features/undo_redo/store/MapHistoryStore.ts
  frontend/src/features/undo_redo/store/action-types.ts
  frontend/src/features/undo_redo/store/state-types.ts
Labels: please review

#337 Feature/334 toolbar integration
  frontend/src/components/Button/IconButton.stories.tsx
  frontend/src/components/Button/IconButton.tsx
  frontend/src/components/Slider/NamedSlider.tsx
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/components/toolbar/LayerList.stories.tsx
  frontend/src/features/map_planning/components/toolbar/LayerList.tsx
  frontend/src/features/map_planning/components/toolbar/LayerSettings.stories.tsx
  frontend/src/features/map_planning/components/toolbar/Layers.tsx
  frontend/src/features/map_planning/components/toolbar/PlantSearch.tsx
  frontend/src/features/map_planning/routes/Map.tsx
  frontend/src/features/undo_redo/store/MapHistoryStore.test.ts
  frontend/src/features/undo_redo/store/MapHistoryStore.ts
  frontend/src/features/undo_redo/store/state-types.ts
Labels: please review, please merge

#362 Agenda for 23.5.2023
  doc/meetings/2023_05_23.md
  doc/milestones.md
  doc/usecases/README.md
Labels: please review

#352 docs(frontend): add architecture docs
  doc/architecture/frontend.md
  doc/contrib/frontend.md
Labels: please review

#378 Feature/339 frontend refactor map state
  doc/architecture/frontend.md
  frontend/__mocks__/zustand.ts
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/components/toolbar/LayerList.tsx
  frontend/src/features/map_planning/components/toolbar/Layers.tsx
  frontend/src/features/map_planning/routes/Map.tsx
  frontend/src/features/map_planning/store/MapStore.test.ts
  frontend/src/features/map_planning/store/MapStore.ts
  frontend/src/features/map_planning/store/MapStoreTypes.ts
  frontend/src/features/map_planning/store/TrackedMapStore.ts
  frontend/src/features/map_planning/store/UntrackedMapStore.ts
  frontend/src/features/undo_redo/index.ts
  frontend/src/features/undo_redo/store/MapHistoryStore.ts
  frontend/src/features/undo_redo/store/action-types.ts
  frontend/src/features/undo_redo/store/state-types.ts
Labels: please review, please merge

#376 365 bug auth breaks landing page when backend is down
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/Providers.tsx
  frontend/src/config/i18n/de/auth.json
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/en/auth.json
  frontend/src/features/auth/components/LoginButton.tsx
  frontend/src/hooks/useSafeAuth.tsx
Labels: please merge

#381 364 nextcloud integration get images
  doc/setups/nextcloud/README.md
  frontend/.env.sample
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/config/axios/index.ts
  frontend/src/config/nextcloud_client/index.ts
  frontend/src/features/nextcloud_integration/api/getImages.ts
  frontend/src/features/nextcloud_integration/components/ImageBlob.tsx
  frontend/src/features/nextcloud_integration/components/webdav-test.tsx
  frontend/src/routes/index.ts
  frontend/src/routes/types.ts
  frontend/src/utils/getUser.ts
Labels: please review, please merge

#367 #258 plants full-text search
  backend/migrations/2023-05-21-111800_pg_trgm_extension/down.sql
  backend/migrations/2023-05-21-111800_pg_trgm_extension/up.sql
  backend/src/controller/plants.rs
  backend/src/db/function.rs
  backend/src/db/pagination.rs
  backend/src/error.rs
  backend/src/model/dto/plants_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/plants_impl.rs
  backend/src/model/enum/water_requirement.rs
  backend/src/service/plants.rs
  doc/decisions/search_plants.md
  doc/usecases/current/search_plants.md
  frontend/src/features/map_planning/components/toolbar/PlantSearch.tsx
Labels: please merge
