Repository ElektraInitiative/PermaplanT, pull requests merged in 2023-04, with the labels that each got.

#166 Polyculture Use Case: Add Plant Relationships
  doc/architecture/glossary.md
  doc/usecases/polyculture/add_plant_relationships.md
Labels: documentation, please review

#165 Polyculture Use Case: Incomplete Groups
  doc/usecases/polyculture/incomplete_groups.md
Labels: documentation, please review

#196 feat: #152 landing page improvements
  frontend/package-lock.json
  frontend/package.json
  frontend/public/github-mark/github-mark.svg
  frontend/src/App.tsx
  frontend/src/assets/globe.svg
  frontend/src/assets/permaplant-logo-2.svg
  frontend/src/assets/permaplant-logo-dark.svg
  frontend/src/assets/permaplant-logo.svg
  frontend/src/assets/planning.svg
  frontend/src/assets/plant.svg
  frontend/src/components/Button/ButtonLink.tsx
  frontend/src/components/Card/SimpleCard.tsx
  frontend/src/components/Layout/Footer.tsx
  frontend/src/components/Layout/NavContainer.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/WidePageLayout.tsx
  frontend/src/features/landing_page/components/BlogOverview.tsx
  frontend/src/features/landing_page/components/CTA.tsx
  frontend/src/features/landing_page/components/ContactUs.tsx
  frontend/src/features/landing_page/components/DarkModeSwitcher.tsx
  frontend/src/features/landing_page/components/Features.tsx
  frontend/src/features/landing_page/components/GeoMap.tsx
  frontend/src/features/landing_page/components/Navbar.tsx
  frontend/src/features/landing_page/components/PhotoGallery.tsx
  frontend/src/features/landing_page/components/Pricing.tsx
  frontend/src/features/landing_page/components/Team.tsx
  frontend/src/features/landing_page/components/Testimonials.tsx
  frontend/src/features/landing_page/routes/LandingPage.tsx
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
  frontend/src/routes/index.ts
  frontend/src/styles/globals.css
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: please review

#115 usecases: small fixes & assigments
  .github/PULL_REQUEST_TEMPLATE.md
  doc/architecture/glossary.md
  doc/usecases/buy_seeds.md
  doc/usecases/calender.md
  doc/usecases/copy_paste_selection.md
  doc/usecases/entry_list_seeds.md
  doc/usecases/layers/base_layer.md
  doc/usecases/layers/dimensioning_layer.md
  doc/usecases/layers/drawing_layer.md
  doc/usecases/layers/fertilize_layer.md
  doc/usecases/layers/habitats_layer.md
  doc/usecases/layers/hydrology_layer.md
  doc/usecases/layers/infrastructure_layer.md
  doc/usecases/layers/label_layer.md
  doc/usecases/layers/landscape_layer.md
  doc/usecases/layers/paths_layer.md
  doc/usecases/layers/plants_layer.md
  doc/usecases/layers/shadows_layer.md
  doc/usecases/layers/soil_layer.md
  doc/usecases/layers/terrain_layer.md
  doc/usecases/layers/trees_layer.md
  doc/usecases/layers/warnings_layer.md
  doc/usecases/layers/winds_layer.md
  doc/usecases/layers/zones_layer.md
  doc/usecases/layers_alternatives.md
  doc/usecases/layers_visibility.md
  doc/usecases/login.md
  doc/usecases/map_create_delete.md
  doc/usecases/map_search.md
  doc/usecases/map_statistics.md
  doc/usecases/map_timeline_single_date_selection.md
  doc/usecases/map_undo_redo.md
  doc/usecases/map_versioning.md
  doc/usecases/matchmaking.md
  doc/usecases/measuring_distance.md
  doc/usecases/new_plant.md
  doc/usecases/rename_layers.md
  doc/usecases/review_plant.md
  doc/usecases/translation.md
  doc/usecases/zoom.md
Labels: please review

#198 Merge tables plants and plant_detail and make its data available in frontend.
  .vscode/launch.json
  backend/Cargo.lock
  backend/Cargo.toml
  backend/migrations/2023-03-29-111855_merge_plant_tables/down.sql
  backend/migrations/2023-03-29-111855_merge_plant_tables/up.sql
  backend/src/config/api_doc.rs
  backend/src/config/routes.rs
  backend/src/controller/plants.rs
  backend/src/model/diesel_extensions.rs
  backend/src/model/dto.rs
  backend/src/model/dto/plants_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/plants_impl.rs
  backend/src/model/enum/deciduous_or_evergreen.rs
  backend/src/model/enum/fertility.rs
  backend/src/model/enum/flower_type.rs
  backend/src/model/enum/growth_rate.rs
  backend/src/model/enum/herbaceous_or_woody.rs
  backend/src/model/enum/life_cycle.rs
  backend/src/model/enum/mod.rs
  backend/src/model/enum/nutrition_demand.rs
  backend/src/model/enum/root_zone_tendancy.rs
  backend/src/model/enum/soil_ph.rs
  backend/src/model/enum/soil_texture.rs
  backend/src/model/enum/soil_water_retention.rs
  backend/src/model/enum/sun.rs
  backend/src/model/enum/water.rs
  backend/src/model/mod.rs
  backend/src/service/plants.rs
  backend/src/test/mod.rs
  backend/src/test/plant.rs
  backend/src/test/seed.rs
  backend/src/test/test_utils.rs
  frontend/src/components/Form/CreatableSelectMenu.tsx
  frontend/src/components/Form/SelectMenu.tsx
  frontend/src/components/Form/SimpleFormInput.tsx
  frontend/src/components/TransparentBackground.tsx
  frontend/src/config/index.ts
  frontend/src/features/seeds/api/findAllPlants.ts
  frontend/src/features/seeds/api/findPlantById.ts
  frontend/src/features/seeds/api/searchPlants.ts
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/features/seeds/routes/CreateSeed.tsx
  frontend/src/features/seeds/routes/SeedDetails.tsx
  frontend/src/features/seeds/store/CreateSeedStore.ts
  frontend/src/hooks/useDebouncedValue.tsx
  frontend/src/hooks/usePreventNavigation.ts
  frontend/src/utils/map-error-to-string.ts
  frontend/vite.config.ts
  scraper/migrate_plant_detail_to_plant.sql
  scraper/src/insert_plant_details.js
Labels: enhancement, please review

#214 Added color themes to frontend
  frontend/src/components/Button/SimpleButton.tsx
  frontend/src/components/Form/CreatableSelectMenu.tsx
  frontend/src/components/Form/SearchInput.tsx
  frontend/src/components/Form/SelectMenu.tsx
  frontend/src/components/Form/SimpleFormInput.tsx
  frontend/src/components/Layout/Footer.tsx
  frontend/src/features/landing_page/components/BlogOverview.tsx
  frontend/src/features/landing_page/components/CTA.tsx
  frontend/src/features/landing_page/components/ContactUs.tsx
  frontend/src/features/landing_page/components/Features.tsx
  frontend/src/features/landing_page/components/PhotoGallery.tsx
  frontend/src/features/landing_page/components/Pricing.tsx
  frontend/src/features/landing_page/components/Team.tsx
  frontend/src/features/landing_page/components/Testimonials.tsx
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/tailwind.config.js
Labels: please review

#168 Polyculture Use Case: Map Specific Favorite Groups
  doc/usecases/polyculture/map_specific_favorite_groups.md
Labels: documentation, please review

#169 Polyculture Use Case: Search Plants
  doc/usecases/polyculture/search_plants.md
Labels: documentation, please review

#167 Polyculture Use Case: Review Plant Relationships
  doc/usecases/polyculture/review_plant_relationships.md
Labels: documentation, please review

#161 decision: frontend documentation
  doc/contrib/frontend.md
  doc/decisions/frontend_documentation.md
Labels: please review

#207 Performance audit tool
  benchmarks/.gitignore
  benchmarks/README.md
  benchmarks/package-lock.json
  benchmarks/package.json
  benchmarks/playwright.config.js
  benchmarks/tests/performance-audit.spec.js
Labels: please review

#227 2023_04_11.md
  doc/meetings/2023_04_07_db.md
  doc/meetings/2023_04_07_frontend.md
  doc/meetings/2023_04_11.md
  doc/milestones.md
Labels: meeting

#156 Architecture decisions of the canvas
  .gitignore
  doc/architecture/glossary.md
  doc/decisions/frontend_state_offloading.md
  doc/decisions/map_lazyloading.md
  doc/decisions/map_undo_redo_implementation.md
Labels: please review

#235 Introduce i18next
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form/SearchInput.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/PageLayout.tsx
  frontend/src/config/env.ts
  frontend/src/config/i18n/@types/i18next.d.ts
  frontend/src/config/i18n/de/common.json
  frontend/src/config/i18n/de/enums.json
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/de/seeds.json
  frontend/src/config/i18n/en/common.json
  frontend/src/config/i18n/en/enums.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/config/i18n/en/seeds.json
  frontend/src/config/i18n/index.ts
  frontend/src/config/index.ts
  frontend/src/features/landing_page/components/LanguageSwitcher.tsx
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
  frontend/src/features/seeds/routes/CreateSeed.tsx
  frontend/src/features/seeds/routes/SeedDetails.tsx
  frontend/src/features/seeds/routes/ViewSeeds.tsx
  frontend/src/utils/enum.ts
  frontend/src/utils/translated-enums.ts
Labels: please review

#273 fix: add stylesConfig for PaginatedSelectMenu
  frontend/src/components/Form/PaginatedSelectMenu.tsx
Labels: please review

#272 fix: select menu text disapears on click
  frontend/src/components/Form/CreatableSelectMenu.tsx
  frontend/src/components/Form/PaginatedSelectMenu.tsx
  frontend/src/components/Form/SelectMenu.tsx
Labels: please review

#271 Fix content padding.
  frontend/src/components/Layout/NavContainer.tsx
  frontend/src/components/Layout/PageLayout.tsx
Labels: please review

#279 Adjusted blues in color theme
  frontend/tailwind.config.js
Labels: please review

#283 pre-commit: make prettier sort imports
  .pre-commit-config.yaml
Labels: please review

#286 Introduce Storybook
  .pre-commit-config.yaml
  doc/contrib/frontend.md
  frontend/.eslintrc.js
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.npmrc
  frontend/.storybook/main.ts
  frontend/.storybook/preview-head.html
  frontend/.storybook/preview.ts
  frontend/.storybook/storybook.css
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button/ButtonLink.stories.tsx
  frontend/src/components/Button/ButtonLink.tsx
  frontend/src/components/Button/SimpleButton.stories.tsx
  frontend/src/components/Button/SimpleButton.tsx
  frontend/src/config/i18n/@types/i18next.d.ts
  frontend/src/features/landing_page/components/LanguageSwitcher.tsx
  frontend/src/features/landing_page/index.ts
  frontend/src/features/seeds/index.ts
  frontend/src/utils/stories/react-router-decorators.tsx
  frontend/tsconfig.json
  frontend/typedoc.json
Labels: please review

#285 Added imprint page
  frontend/src/components/Layout/Footer.tsx
  frontend/src/config/i18n/de/imprint.json
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/en/imprint.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/features/imprint_page/index.ts
  frontend/src/features/imprint_page/routes/ImprintPage.tsx
  frontend/src/routes/index.ts
  frontend/src/routes/types.ts
Labels: please review

#276 Generalize Pagination
  backend/src/config/api_doc.rs
  backend/src/config/mod.rs
  backend/src/config/routes.rs
  backend/src/controller/plants.rs
  backend/src/controller/seed.rs
  backend/src/db/connection.rs
  backend/src/db/function.rs
  backend/src/db/mod.rs
  backend/src/db/pagination.rs
  backend/src/main.rs
  backend/src/model/dto.rs
  backend/src/model/dto/page_impl.rs
  backend/src/model/entity/plants_impl.rs
  backend/src/model/entity/seed_impl.rs
  backend/src/model/mod.rs
  backend/src/service/plants.rs
  backend/src/service/seed.rs
  backend/src/test/plant.rs
  backend/src/test/test_utils.rs
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Form/PaginatedSelectMenu.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/PageLayout.tsx
  frontend/src/components/Layout/WidePageLayout.tsx
  frontend/src/components/Modals/ModalContainer.tsx
  frontend/src/components/TransparentBackground.tsx
  frontend/src/features/landing_page/components/BlogOverview.tsx
  frontend/src/features/landing_page/components/CTA.tsx
  frontend/src/features/landing_page/components/ContactUs.tsx
  frontend/src/features/landing_page/components/Pricing.tsx
  frontend/src/features/landing_page/routes/LandingPage.tsx
  frontend/src/features/seeds/api/findAllSeeds.ts
  frontend/src/features/seeds/api/searchPlants.ts
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
  frontend/src/features/seeds/routes/ViewSeeds.tsx
  frontend/src/features/seeds/store/CreateSeedStore.ts
  frontend/src/features/seeds/store/FindSeedsStore.ts
Labels: please merge

#259 14.04.2023
  doc/meetings/2023_04_18.md
Labels: meeting

#292 Load map only after click
  frontend/src/config/i18n/de/geomap.json
  frontend/src/config/i18n/de/index.ts
  frontend/src/config/i18n/en/geomap.json
  frontend/src/config/i18n/en/index.ts
  frontend/src/features/landing_page/components/BlogOverview.tsx
  frontend/src/features/landing_page/components/ContactUs.tsx
  frontend/src/features/landing_page/components/Features.tsx
  frontend/src/features/landing_page/components/GeoMap.tsx
  frontend/src/features/landing_page/components/Pricing.tsx
Labels: please review

#215 feat: drawing layer
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/index.ts
  frontend/src/features/map_planning/layers/PlantsLayer.tsx
  frontend/src/features/map_planning/routes/Map.tsx
  frontend/src/features/map_planning/types/SelectionRectAttrs.ts
  frontend/src/features/map_planning/utils/ShapesSelection.ts
  frontend/src/features/map_planning/utils/StageTransform.ts
  frontend/src/routes/index.ts
  frontend/src/routes/types.ts
Labels: please merge

#301 Bug fix/300 mixture of languages
  frontend/package-lock.json
  frontend/src/features/landing_page/components/Features.tsx
Labels: please review

#105 Onboarding PR: first gamification use cases
  doc/usecases/gamification/diversity_score.md
  doc/usecases/gamification/experimental_results.md
  doc/usecases/gamification/gain_blossoms.md
  doc/usecases/gamification/map_honors.md
  doc/usecases/gamification/plant_lore.md
  doc/usecases/gamification/reward_preview.md
Labels: please review

#282 Frontend testing
  doc/tests/frontend.md
  frontend/README.md
  frontend/babel.config.js
  frontend/jest.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button/ButtonLink.test.tsx
  frontend/src/components/Button/SimpleButton.test.tsx
  frontend/src/components/Button/__snapshots__/ButtonLink.test.tsx.snap
  frontend/src/components/Button/__snapshots__/SimpleButton.test.tsx.snap
  frontend/src/components/Card/SimpleCard.test.tsx
  frontend/src/components/Card/__snapshots__/SimpleCard.test.tsx.snap
  frontend/src/components/Form/CreatableSelectMenu.test.tsx
  frontend/src/components/Form/CreatableSelectMenu.tsx
  frontend/src/components/Form/PaginatedSelectMenu.test.tsx
  frontend/src/components/Form/PaginatedSelectMenu.tsx
  frontend/src/components/Form/SearchInput.test.tsx
  frontend/src/components/Form/SelectMenu.test.tsx
  frontend/src/components/Form/SelectMenu.tsx
  frontend/src/components/Form/SimpleFormInput.test.tsx
  frontend/src/components/Form/__snapshots__/CreatableSelectMenu.test.tsx.snap
  frontend/src/components/Form/__snapshots__/PaginatedSelectMenu.test.tsx.snap
  frontend/src/components/Form/__snapshots__/SearchInput.test.tsx.snap
  frontend/src/components/Form/__snapshots__/SelectMenu.test.tsx.snap
  frontend/src/components/Form/__snapshots__/SimpleFormInput.test.tsx.snap
  frontend/src/components/Header/PageTitle.test.tsx
  frontend/src/components/Header/__snapshots__/PageTitle.test.tsx.snap
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Modals/ImageModal.test.tsx
  frontend/src/components/Modals/ImageModal.tsx
  frontend/src/components/Modals/ModalContainer.test.tsx
  frontend/src/components/Modals/SimpleModal.test.tsx
  frontend/src/components/Modals/SimpleModal.tsx
  frontend/src/components/Modals/__snapshots__/ImageModal.test.tsx.snap
  frontend/src/components/Modals/__snapshots__/ModalContainer.test.tsx.snap
  frontend/src/components/Modals/__snapshots__/SimpleModal.test.tsx.snap
  frontend/src/features/landing_page/components/LanguageSwitcher.tsx
  frontend/src/utils/testing.tsx
  frontend/svg-transform.ts
  frontend/tsconfig.json
Labels: please review
