Repository ElektraInitiative/PermaplanT, pull requests merged in 2023-09, with the labels that each got.

#884 Bug fix/817 middle mouse dragging and selection
  doc/changelog.md
  frontend/src/features/map_planning/components/BaseStage.tsx
Labels: release critical

#852 E2E: New test for select box
  doc/changelog.md
  e2e/features/planting_select.feature
  e2e/pages/maps/planting.py
  e2e/steps/test_planting.py
  e2e/steps/test_planting_select.py
  e2e/steps/test_timeline.py
  e2e/steps/test_undo_redo.py
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/utils/ShapesSelection.ts
Labels: bug, please review, e2e

#889 Undo plant deletion test
  doc/changelog.md
  e2e/features/undo_redo.feature
  e2e/pages/maps/planting.py
  e2e/steps/test_undo_redo.py
Labels: e2e

#864 Update test strategy
  doc/changelog.md
  doc/tests/README.md
Labels: documentation

#881 Seed delete confirmation and undo.
  backend/migrations/2023-09-02-153556_archivable_seeds/down.sql
  backend/migrations/2023-09-02-153556_archivable_seeds/up.sql
  backend/src/config/routes.rs
  backend/src/controller/seed.rs
  backend/src/model/dto.rs
  backend/src/model/dto/seed_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/seed_impl.rs
  backend/src/model/enum/include_archived_seeds.rs
  backend/src/model/enum/mod.rs
  backend/src/service/seed.rs
  backend/src/test/seed.rs
  doc/changelog.md
  doc/usecases/current/entry_list_seeds.md
  frontend/src/config/i18n/de/seeds.json
  frontend/src/config/i18n/en/seeds.json
  frontend/src/features/seeds/api/archiveSeed.ts
  frontend/src/features/seeds/api/createSeed.ts
  frontend/src/features/seeds/api/deleteSeed.ts
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
  frontend/src/features/seeds/routes/ViewSeeds.tsx
  frontend/src/hooks/useTranslateQuantity.ts
  frontend/src/icons/archive-off.svg
Labels: release critical

#681 Add dependencies to makefile install target
  .gitignore
  Makefile
  README.md
  backend/Makefile
  ci/Jenkinsfile
  doc/changelog.md
  doc/contrib/README.md
  doc/development_setup.md
  e2e/README.md
  e2e/e2e.sh
  e2e/install.sh
  e2e/uninstall.sh
Labels: enhancement

#917 Reduce E2E entry barriers
  README.md
  doc/changelog.md
  e2e/.env.sample
  e2e/README.md
Labels: please merge

#931 Tag docker images
  ci/Jenkinsfile
  doc/changelog.md
Labels: please merge, CI

#926 Fix order of name parts in plant name.
  doc/changelog.md
  frontend/src/components/ExtendedPlantDisplay.tsx
Labels: please merge

#933 Make plant name in select menu consistent with seed overview.
  doc/changelog.md
  frontend/src/features/seeds/components/CreateSeedForm.tsx
Labels: please review

#934 Fix harvest year column title wrapping inappropriately.
  doc/changelog.md
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
Labels: please review

#932 Add seed search to use case.
  doc/changelog.md
  doc/usecases/current/entry_list_seeds.md
Labels: documentation, please review
