Repository ElektraInitiative/PermaplanT, pull requests merged in 2023-03, with the labels that each got.

#82 Meeting notes/14.03.2023
  doc/meetings/2023_03_14.md
  doc/meetings/template.md
Labels: meeting

#124 doc: add meeting agenda
  doc/meetings/2023_03_20_db_kick_off.md
Labels: meeting

#116 meeting notes: focus group 'Gamification' 15.03.2023
  doc/meetings/2023_03_15_gamification.md
Labels: please review

#147 fix(seeds): better error messages
  frontend/src/config/index.ts
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/features/seeds/routes/CreateSeed.tsx
  frontend/src/main.tsx
  frontend/src/utils/map-error-to-string.ts
Labels: please review

#110 meeting: add agenda for 21.03.2023
  doc/meetings/2023_03_21.md
Labels: please review, meeting

#133 docs: add links for frontend contribution
  doc/contrib/frontend.md
Labels: please review

#104 Improve frontend documentation.
  doc/ui_components/Button/SimpleButton.md
  doc/ui_components/Form/CreatableSelectMenu.md
  doc/ui_components/Form/SelectMenu.md
  doc/ui_components/Form/SimpleFormInput.md
  doc/ui_components/Header/PageTitle.md
  doc/ui_components/Modal/ModalContainer.md
  doc/ui_components/Modal/SimpleModal.md
  doc/ui_components/TansparentBackground.md
Labels: documentation, please review

#154 meeting notes 28.3.023
  .github/CONTRIBUTING.md
  doc/meetings/2023_03_28.md
Labels: please review, meeting

#107 84 landing page prototype
  doc/ui_components/Button/SimpleButton.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/gallery_images/permaplant_illustration_01.svg
  frontend/public/gallery_images/permaplant_illustration_02.svg
  frontend/public/gallery_images/permaplant_illustration_03.svg
  frontend/public/gallery_images/permaplant_illustration_04.svg
  frontend/public/gallery_images/permaplant_illustration_05.svg
  frontend/public/gallery_images/permaplant_illustration_06.svg
  frontend/public/gallery_images/permaplant_illustration_07.svg
  frontend/public/gallery_images/permaplant_illustration_08.svg
  frontend/public/gallery_images/permaplant_illustration_09.svg
  frontend/public/gallery_images/permaplant_illustration_10.svg
  frontend/public/gallery_images/permaplant_illustration_11.svg
  frontend/public/gallery_images/permaplant_illustration_12.svg
  frontend/public/github-mark/github-mark-white.png
  frontend/public/github-mark/github-mark-white.svg
  frontend/public/github-mark/github-mark.png
  frontend/public/github-mark/github-mark.svg
  frontend/public/permaplant-logo-2.svg
  frontend/public/permaplant-logo.svg
  frontend/public/permaplant_drawing.jpeg
  frontend/src/App.tsx
  frontend/src/Root.tsx
  frontend/src/components/Button/SimpleButton.tsx
  frontend/src/components/Form/CreatableSelectMenu.tsx
  frontend/src/components/Form/SearchInput.tsx
  frontend/src/components/Form/SelectMenu.tsx
  frontend/src/components/Form/SimpleFormInput.tsx
  frontend/src/components/Modals/ImageModal.tsx
  frontend/src/components/Modals/ModalContainer.tsx
  frontend/src/components/Modals/SimpleModal.tsx
  frontend/src/components/TransparentBackground.tsx
  frontend/src/features/landing_page/components/DarkModeSwitcher.tsx
  frontend/src/features/landing_page/components/GeoMap.tsx
  frontend/src/features/landing_page/components/Navbar.tsx
  frontend/src/features/landing_page/components/PhotoGallery.tsx
  frontend/src/features/landing_page/index.ts
  frontend/src/features/landing_page/routes/LandingPage.tsx
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
  frontend/src/features/seeds/routes/ViewSeeds.tsx
  frontend/src/routes/index.ts
  frontend/src/routes/types.ts
  frontend/src/styles/geoMap.css
  frontend/src/styles/globals.css
  frontend/src/tailwind-theme.js
  frontend/src/tailwind.config.js
  frontend/src/utils/filterObject.ts
  frontend/tailwind.config.js
Labels: please review

#145 load baseApiUrl from env file
  ci/build-scripts/build-frontend.sh
  frontend/.env.sample
  frontend/.gitignore
  frontend/README.md
  frontend/src/config/index.ts
Labels: please review

#188 fixes #187
  frontend/src/App.tsx
Labels: please review
