Repository ElektraInitiative/PermaplanT, pull requests merged in 2023-10, with the labels that each got.

#930 Cargo deny checks
  backend/Cargo.lock
  backend/Cargo.toml
  backend/deny.toml
  doc/changelog.md
Labels: please merge

#935 Fix text area only allowing one line of text in create seed menu.
  doc/changelog.md
  frontend/src/components/Form/SimpleFormTextArea.tsx
  frontend/src/features/seeds/components/CreateSeedForm.tsx
Labels: please review

#939 Add 200ms timeout before clicking on canvas
  doc/changelog.md
  e2e/pages/maps/planting.py
Labels: e2e

#941 Reimplement facilities for name display.
  doc/changelog.md
  frontend/src/components/ExtendedPlantDisplay.tsx
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantLabel.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantingElement.tsx
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
  frontend/src/utils/ExtendedPlantsSummary.tsx
  frontend/src/utils/plant-naming.test.tsx
  frontend/src/utils/plant-naming.tsx
Labels: release critical

#971 Fix mdbook build in release pipeline
  ci/Jenkinsfile.release
  doc/changelog.md
Labels: release critical

#973 Refactor data-testid's and add other missing locators
  doc/changelog.md
  doc/guidelines/frontend-locators.md
  e2e/pages/maps/create.py
  e2e/pages/maps/planting.py
  e2e/steps/test_map_creation.py
  frontend/src/components/Form/PaginatedSelectMenu.tsx
  frontend/src/components/Form/SearchInput.tsx
  frontend/src/components/Form/SelectMenu.tsx
  frontend/src/components/Form/__snapshots__/PaginatedSelectMenu.test.tsx.snap
  frontend/src/components/Form/__snapshots__/SearchInput.test.tsx.snap
  frontend/src/components/Form/__snapshots__/SelectMenu.test.tsx.snap
  frontend/src/features/landing_page/components/LanguageSwitcher.tsx
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/components/Map.tsx
  frontend/src/features/map_planning/components/toolbar/LayerListItem.tsx
  frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantSearch.tsx
  frontend/src/features/maps/components/MapCard.tsx
  frontend/src/features/maps/routes/MapCreateForm.tsx
  frontend/src/features/seeds/components/CreateSeedForm.tsx
Labels: please review, please merge, e2e

#924 docs: create multi-select usecase
  doc/changelog.md
  doc/usecases/current/multi_select.md
Labels: please merge

#980 feat: improve vertical scrollbars of toolbars
  doc/changelog.md
  frontend/src/features/map_planning/components/toolbar/Toolbar.tsx
Labels: please merge

#992 Feature/871 improve guided tour text
  doc/changelog.md
  frontend/src/components/Button/SimpleButton.tsx
  frontend/src/components/Button/__snapshots__/SimpleButton.test.tsx.snap
  frontend/src/config/i18n/de/guidedTour.json
  frontend/src/config/i18n/en/guidedTour.json
  frontend/src/features/map_planning/components/Map.tsx
  frontend/src/features/map_planning/utils/EditorTour.ts
  frontend/src/styles/guidedTour.css
  frontend/typedoc.json
Labels: please merge

#1001 Finish seed use case.
  doc/changelog.md
  doc/usecases/assigned/buy_seeds.md
  doc/usecases/done/entry_list_seeds.md
Labels: please merge

#921 docs: rewrite and split first copy and paste usecase
  doc/changelog.md
  doc/usecases/current/copy_paste_selection.md
  doc/usecases/current/copy_paste_within_same_map.md
  doc/usecases/draft/copy_paste_between_own_maps.md
  doc/usecases/draft/copy_paste_between_users.md
  doc/usecases/draft/copy_paste_via_icons.md
Labels: please merge

#950 Documentation/860 decision api mock tool
  doc/changelog.md
  doc/decisions/frontend_mocking_tool.md
Labels: please merge

#907 Run E2E tests on dev.permaplant
  ci/Jenkinsfile
  doc/changelog.md
Labels: please review, CI
