Repository ElektraInitiative/PermaplanT, pull requests merged in 2023-06, with the labels that each got.

#287 Added more table definitions and ER diagrams
  doc/database/schemata.md
Labels: please review

#412 Auth documentation
  backend/.env.sample
  backend/README.md
  doc/backend/01setup.md
  doc/backend/02obtain_access_tokens.md
  doc/backend/03api_documentation.md
  doc/backend/README.md
  doc/setups/README.md
  doc/usecases/done/login.md
Labels: documentation, please review, please merge

#414 map search backend
  backend/src/db/function.rs
  backend/src/model/dto.rs
  backend/src/model/dto/map_impl.rs
  backend/src/model/dto/plants_impl.rs
  backend/src/model/entity/map_impl.rs
  backend/src/model/entity/plants_impl.rs
  backend/src/test/map.rs
Labels: please review, please merge

#410 Additional map properties during map creation
  backend/Cargo.lock
  backend/Cargo.toml
  backend/diesel.toml
  backend/migrations/2023-05-29-210302_additional_map_properties/down.sql
  backend/migrations/2023-05-29-210302_additional_map_properties/up.sql
  backend/src/model/dto.rs
  backend/src/model/dto/coordinates_impl.rs
  backend/src/model/dto/map_impl.rs
  backend/src/model/dto/new_map_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/map_impl.rs
  backend/src/model/enum/mod.rs
  backend/src/model/enum/privacy_options.rs
  backend/src/schema.patch
  backend/src/test/map.rs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/config/i18n/de/maps.json
  frontend/src/config/i18n/en/maps.json
  frontend/src/features/maps/components/MapCard.tsx
  frontend/src/features/maps/components/MapCreateModal.tsx
  frontend/src/features/maps/index.ts
  frontend/src/features/maps/routes/MapCreateForm.tsx
  frontend/src/features/maps/routes/MapOverview.tsx
  frontend/src/routes/index.ts
  frontend/src/routes/types.ts
Labels: please review

#449 Connect map owner_id with logged-in user
  backend/Cargo.lock
  backend/Cargo.toml
  backend/migrations/2023-06-12-110743_map_owner_uuid/down.sql
  backend/migrations/2023-06-12-110743_map_owner_uuid/up.sql
  backend/src/controller/map.rs
  backend/src/model/dto.rs
  backend/src/model/dto/map_impl.rs
  backend/src/model/dto/new_map_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/map_impl.rs
  backend/src/service/map.rs
  backend/src/test/map.rs
  frontend/src/features/maps/api/findAllMaps.ts
  frontend/src/features/maps/routes/MapCreateForm.tsx
  frontend/src/features/maps/routes/MapOverview.tsx
Labels: please review

#427 Plant Layer API + DB
  backend/Cargo.lock
  backend/Cargo.toml
  backend/migrations/2023-06-11-122400_plantings/down.sql
  backend/migrations/2023-06-11-122400_plantings/up.sql
  backend/src/config/api_doc.rs
  backend/src/config/routes.rs
  backend/src/controller/layers.rs
  backend/src/controller/mod.rs
  backend/src/controller/plantings.rs
  backend/src/model/dto.rs
  backend/src/model/dto/actions.rs
  backend/src/model/dto/plantings.rs
  backend/src/model/dto/plantings_impl.rs
  backend/src/model/entity.rs
  backend/src/model/entity/layer_impl.rs
  backend/src/model/entity/plantings.rs
  backend/src/model/entity/plantings_impl.rs
  backend/src/service/layer.rs
  backend/src/service/mod.rs
  backend/src/service/plantings.rs
  backend/src/test/layers.rs
  backend/src/test/mod.rs
  backend/src/test/plantings.rs
  doc/database/schemata/01er_diagram.md
  doc/database/schemata/02table_descriptions.md
  doc/database/schemata/03example_queries.md
  doc/database/schemata/README.md
  frontend/src/features/map_planning/api/movePlanting.ts
  frontend/src/features/map_planning/api/transformPlanting.ts
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/layers/plant/actions.ts
  frontend/src/features/map_planning/store/MapStore.test.ts
Labels: please review

#491 Fixed long waiting times for map overview to update
  frontend/src/features/maps/routes/MapCreateForm.tsx
  frontend/src/features/maps/routes/MapOverview.tsx
Labels: please review

#455 Updated location picker to only load on user click
  frontend/src/config/i18n/de/maps.json
  frontend/src/config/i18n/en/maps.json
  frontend/src/features/maps/routes/MapCreateForm.tsx
Labels: please review

#448 faster Pipeline Jenkins, by merging Check- and Build-Stage
  backend/.cargo/config.toml
  ci/Jenkinsfile
Labels: urgent

#488 Map editor connected to map
  backend/src/controller/layers.rs
  backend/src/model/dto/plantings.rs
  backend/src/model/entity/layer_impl.rs
  backend/src/model/entity/plantings_impl.rs
  backend/src/service/layer.rs
  backend/src/test/layers.rs
  backend/src/test/plantings.rs
  frontend/src/features/map_planning/api/getLayers.ts
  frontend/src/features/map_planning/api/getPlantings.ts
  frontend/src/features/map_planning/components/Map.tsx
  frontend/src/features/map_planning/components/toolbar/LayerList.tsx
  frontend/src/features/map_planning/components/toolbar/Layers.tsx
  frontend/src/features/map_planning/hooks/useGetLayers.tsx
  frontend/src/features/map_planning/hooks/useMapId.tsx
  frontend/src/features/map_planning/index.ts
  frontend/src/features/map_planning/layers/base/actions.ts
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/features/map_planning/layers/plant/actions.ts
  frontend/src/features/map_planning/layers/plant/components/PlantLayerLeftToolbar.tsx
  frontend/src/features/map_planning/layers/plant/hooks/useSelectedPlantForPlanting.ts
  frontend/src/features/map_planning/routes/MapWrapper.tsx
  frontend/src/features/map_planning/store/MapStore.test.ts
  frontend/src/features/map_planning/store/MapStoreTypes.ts
  frontend/src/features/map_planning/store/TrackedMapStore.ts
  frontend/src/features/map_planning/store/UntrackedMapStore.ts
  frontend/src/routes/index.ts
Labels: please review

#432 Feature/396 load gallery images from nextcloud
  doc/usecases/current/plants_layer.md
  frontend/src/components/Modals/ImageModal.tsx
  frontend/src/components/Modals/__snapshots__/ImageModal.test.tsx.snap
  frontend/src/config/i18n/de/blog.json
  frontend/src/config/i18n/en/blog.json
  frontend/src/features/landing_page/components/BlogOverview.tsx
  frontend/src/features/landing_page/components/GeoMap.tsx
  frontend/src/features/landing_page/components/PhotoGallery.tsx
  frontend/src/features/landing_page/components/Team.tsx
  frontend/src/features/landing_page/components/Teammember.tsx
  frontend/src/features/nextcloud_integration/api/getImages.ts
  frontend/src/features/nextcloud_integration/components/ImageBlob.tsx
  frontend/src/features/nextcloud_integration/components/NextcloudImage.tsx
  frontend/src/features/nextcloud_integration/components/PublicNextcloudImage.tsx
  frontend/src/features/nextcloud_integration/components/webdav-test.tsx
  frontend/src/icons/chevron-left.svg
  frontend/src/icons/chevron-right.svg
Labels: please review

#487 add plants relations endpoint
  backend/migrations/2023-06-20-110200_plants_relations/down.sql
  backend/migrations/2023-06-20-110200_plants_relations/up.sql
  backend/src/config/api_doc.rs
  backend/src/config/routes.rs
  backend/src/controller/mod.rs
  backend/src/controller/plant_layer.rs
  backend/src/controller/plants.rs
  backend/src/model/dto.rs
  backend/src/model/entity.rs
  backend/src/model/entity/plant_layer.rs
  backend/src/model/enum/mod.rs
  backend/src/model/enum/relation_type.rs
  backend/src/service/mod.rs
  backend/src/service/plant_layer.rs
  backend/src/test/mod.rs
  backend/src/test/plant_layer.rs
  doc/database/schemata/01er_diagram.md
  doc/database/schemata/02table_descriptions.md
Labels: please review, please merge

#497 Feature/492 plants layer UI ux improvements
  backend/src/model/dto.rs
  frontend/src/App.tsx
  frontend/src/components/Button/IconButton.tsx
  frontend/src/components/Slider/NamedSlider.tsx
  frontend/src/config/i18n/de/undoRedo.json
  frontend/src/config/i18n/en/undoRedo.json
  frontend/src/config/nextcloud_client/index.ts
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/components/Map.tsx
  frontend/src/features/map_planning/components/NextcloudKonvaImage.tsx
  frontend/src/features/map_planning/components/image/NextcloudKonvaImage.stories.ts
  frontend/src/features/map_planning/components/image/NextcloudKonvaImage.tsx
  frontend/src/features/map_planning/components/image/PublicNextcloudKonvaImage.stories.tsx
  frontend/src/features/map_planning/components/image/PublicNextcloudKonvaImage.tsx
  frontend/src/features/map_planning/components/toolbar/Layers.tsx
  frontend/src/features/map_planning/layers/base/BaseLayer.tsx
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantingElement.tsx
  frontend/src/features/map_planning/store/MapStoreTypes.ts
  frontend/src/features/map_planning/store/UntrackedMapStore.ts
  frontend/src/features/nextcloud_integration/api/getImages.ts
  frontend/src/features/nextcloud_integration/components/NextcloudImage.tsx
  frontend/src/features/nextcloud_integration/components/PublicNextcloudImage.tsx
  frontend/src/features/nextcloud_integration/components/webdav-test.tsx
  frontend/src/features/nextcloud_integration/hooks/useImage.ts
  frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts
  frontend/src/features/nextcloud_integration/hooks/usePublicImage.tsx
  frontend/src/icons/photo-off.svg
  frontend/src/icons/plant.svg
Labels: please review, please merge

#499 add documentation about http headers used by the backend
  doc/backend/04http_header.md
Labels: please review

#519 Test strategy
  .gitignore
  doc/CHANGELOG.md
  doc/architecture/12glossary.md
  doc/authors.md
  doc/tests/README.md
  doc/tests/manual.md
  doc/tests/protocols/README.md
  doc/tests/protocols/template.md
  frontend/src/features/landing_page/components/Team.tsx
Labels: documentation, please review
