Repository ElektraInitiative/PermaplanT, pull requests merged in 2023-11, with the labels that each got.

#1002 add markdown editor for note field in seed form
  doc/changelog.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form/MarkdownEditor.tsx
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/styles/globals.css
Labels: please merge

#1000 Base layer: enable automatic scaling
  doc/changelog.md
  frontend/src/config/i18n/de/baseLayerForm.json
  frontend/src/config/i18n/en/baseLayerForm.json
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/components/EditorMap.tsx
  frontend/src/features/map_planning/layers/base/BaseLayer.tsx
  frontend/src/features/map_planning/layers/base/BaseMeasurementLayer.tsx
  frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/features/map_planning/routes/MapWrapper.tsx
  frontend/src/features/map_planning/store/MapStoreTypes.ts
  frontend/src/features/map_planning/store/UntrackedMapStore.ts
  frontend/src/features/map_planning/types/layer-config.ts
  frontend/src/features/map_planning/utils/Constants.ts
  frontend/src/utils/constants.ts
Labels: please review

#1016 Feature/421 keybinding refactoring
  doc/architecture/12glossary.md
  doc/changelog.md
  frontend/src/components/Form/SearchInput.tsx
  frontend/src/config/keybindings/index.ts
  frontend/src/config/keybindings/keybindings.json
  frontend/src/features/map_planning/components/EditorMap.tsx
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/hooks/useKeyHandlers.tsx
  frontend/src/utils/key-combinations.ts
Labels: please merge

#1051 Fix repeated error toasts
  doc/changelog.md
  frontend/src/App.tsx
  frontend/src/Providers.tsx
  frontend/src/features/debugging/routes/Debug.tsx
  frontend/src/features/map_planning/hooks/useTourStatus.tsx
  frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx
  frontend/src/features/map_planning/layers/plant/components/SeedListItem.tsx
  frontend/src/features/map_planning/layers/plant/hooks/useFindPlantById.ts
  frontend/src/features/map_planning/layers/plant/hooks/useFindPlantFromSeedCallback.ts
  frontend/src/features/map_planning/layers/plant/hooks/useFindSeedById.ts
  frontend/src/features/map_planning/layers/plant/hooks/usePlantSearch.ts
  frontend/src/features/map_planning/layers/plant/hooks/useSeasonalAvailablePlants.ts
  frontend/src/features/map_planning/layers/plant/hooks/useSeedSearch.ts
  frontend/src/features/map_planning/routes/MapWrapper.tsx
  frontend/src/features/map_planning/utils/ReadOnlyModeContext.tsx
  frontend/src/features/maps/routes/MapCreateForm.tsx
  frontend/src/features/maps/routes/MapEditForm.tsx
  frontend/src/features/maps/routes/MapOverview.tsx
  frontend/src/features/nextcloud_integration/components/UploadFile.tsx
  frontend/src/features/nextcloud_integration/hooks/useImageFromBlob.ts
  frontend/src/features/seeds/routes/CreateSeed.tsx
  frontend/src/features/seeds/routes/EditSeed.tsx
  frontend/src/features/seeds/routes/ViewSeeds.tsx
  frontend/src/features/toasts/groupedToast.tsx
  frontend/src/hooks/useSafeAuth.tsx
  frontend/src/routes/index.ts
  frontend/src/routes/types.ts
Labels: please review

#1055 Disable e2e in master
  ci/Jenkinsfile
  doc/changelog.md
Labels: please review, please merge

#994 keybinding concept
  doc/changelog.md
  doc/decisions/frontend_keyhandling.md
  doc/guidelines/frontend-keyhandling.md
Labels: please merge

#1052 Rework base layer form.
  doc/changelog.md
  frontend/src/components/Form/SimpleFormInput.stories.tsx
  frontend/src/components/Form/SimpleFormInput.test.tsx
  frontend/src/components/Form/SimpleFormInput.tsx
  frontend/src/config/i18n/de/baseLayerForm.json
  frontend/src/config/i18n/en/baseLayerForm.json
  frontend/src/features/map_planning/components/BaseStage.tsx
  frontend/src/features/map_planning/components/timeline/Timeline.tsx
  frontend/src/features/map_planning/layers/base/components/BaseLayerAttributeEditForm.tsx
  frontend/src/features/map_planning/layers/base/components/BaseLayerRightToolbar.tsx
  frontend/src/features/map_planning/layers/base/components/DistanceMeasurementModal.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
  frontend/src/features/maps/routes/MapEditForm.tsx
  frontend/src/features/nextcloud_integration/components/FileSelector.tsx
  frontend/src/features/nextcloud_integration/components/chat.tsx
  frontend/src/features/nextcloud_integration/hooks/useFileExists.ts
  frontend/src/features/nextcloud_integration/hooks/useImage.ts
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/svg/icons/close.svg
Labels: please review, please merge

#869 Seed tests
  doc/changelog.md
  e2e/clean_db.py
  e2e/features/seeds.feature
  e2e/features/timeline.feature
  e2e/pages/home.py
  e2e/pages/inventory/create.py
  e2e/pages/inventory/edit.py
  e2e/pages/inventory/management.py
  e2e/pages/maps/create.py
  e2e/pages/maps/edit.py
  e2e/pages/maps/management.py
  e2e/pages/maps/planting.py
  e2e/steps/common_steps.py
  e2e/steps/test_inventory.py
  e2e/steps/test_planting.py
  e2e/steps/test_timeline.py
  e2e/steps/test_undo_redo.py
  frontend/src/components/Form/SelectMenu.tsx
  frontend/src/components/Form/__snapshots__/SelectMenu.test.tsx.snap
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
Labels: please merge, e2e

#1010 E2E increase timeline/baselayer test stability
  doc/changelog.md
  e2e/pages/abstract_page.py
  e2e/pages/home.py
  e2e/pages/maps/planting.py
  frontend/src/features/auth/components/LoginButton.tsx
  frontend/src/features/map_planning/components/timeline/Timeline.tsx
  frontend/src/features/map_planning/layers/base/components/BaseLayerAttributeEditForm.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
Labels: e2e

#1068 feat: delete plants via DEL
  doc/changelog.md
  frontend/src/config/keybindings/keybindings.json
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantLayerLeftToolbar.tsx
  frontend/src/features/map_planning/layers/plant/hooks/useDeleteSelectedPlantings.ts
  frontend/src/features/map_planning/utils/layer-utils.ts
Labels: please review

#1048 fix seeds route and add guideline
  doc/changelog.md
  doc/guidelines/frontend.md
  e2e/pages/inventory/management.py
  frontend/src/features/seeds/routes/ViewSeeds.tsx
  frontend/src/routes/index.ts
Labels: please merge

#1047 refactor: react query error handling using query cache
  doc/changelog.md
  frontend/src/Providers.tsx
  frontend/src/features/map_planning/layers/plant/hooks/useFindPlantById.ts
  frontend/src/features/map_planning/layers/plant/hooks/useFindPlantFromSeedCallback.ts
  frontend/src/features/map_planning/layers/plant/hooks/useFindSeedById.ts
  frontend/src/features/map_planning/layers/plant/hooks/usePlantSearch.ts
  frontend/src/features/map_planning/layers/plant/hooks/useSeasonalAvailablePlants.ts
  frontend/src/features/map_planning/layers/plant/hooks/useSeedSearch.ts
Labels: please merge
