Repository ElektraInitiative/PermaplanT, pull requests merged in 2024-04, with the labels that each got.

#1206 Add documentation for adding a new field to an entity
  doc/architecture/12glossary.md
  doc/backend/07adding_fields_to_entities.md
  doc/changelog.md
Labels: documentation, please merge

#1229 Fix broken darkmode for LanguageSwitcher, SelectMenu & PaginatedSelectMenu
  doc/changelog.md
  frontend/src/components/Form/PaginatedSelectMenu.tsx
  frontend/src/components/Form/SelectMenu.tsx
  frontend/src/components/Form/__snapshots__/PaginatedSelectMenu.test.tsx.snap
  frontend/src/components/Form/__snapshots__/SelectMenu.test.tsx.snap
  frontend/src/features/landing_page/components/LanguageSwitcher.tsx
Labels: bug, please merge

#1235 feat(#1057): add keyhandling for macos
  doc/changelog.md
  doc/guidelines/frontend-keyhandling.md
  frontend/src/config/i18n/de/keybindings.json
  frontend/src/config/i18n/en/keybindings.json
  frontend/src/config/keybindings/index.ts
  frontend/src/config/keybindings/keybindings_macos.json
  frontend/src/config/keybindings/keybindings_windows_linux.json
  frontend/src/hooks/useKeyHandlers.tsx
  frontend/src/utils/key-combinations.ts
Labels: please merge

#1186 Feature/1176 separate fetching of german common names; Data overrides
  ci/Jenkinsfile
  doc/changelog.md
  scraper/README.md
  scraper/package-lock.json
  scraper/package.json
  scraper/src/apply_overrides.js
  scraper/src/fetch_german_names.js
  scraper/src/helpers/helpers.js
  scraper/src/helpers/override.js
  scraper/src/insert_plants.js
  scraper/src/merge_datasets.js
  scraper/src/merge_german_names.js
Labels: please merge

#1246 Fixed German common names not being used when language is set to German
  backend/src/model/dto.rs
  backend/src/model/dto/plants_impl.rs
  backend/src/test/plant.rs
  backend/src/test/util/data.rs
  doc/changelog.md
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantLabel.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantListItem.tsx
  frontend/src/features/map_planning/layers/plant/components/Planting/Planting.tsx
  frontend/src/features/map_planning/layers/plant/components/Planting/utils.ts
  frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
  frontend/src/features/map_planning/layers/plant/components/SeedListItem.tsx
  frontend/src/features/seeds/components/CreateSeedForm.tsx
  frontend/src/features/seeds/components/SeedsOverviewList.tsx
  frontend/src/utils/plant-naming.test.tsx
  frontend/src/utils/plant-naming.tsx
Labels: please review

#1255 305 Fix link preview image
  doc/changelog.md
  frontend/index.html
  frontend/public/apple-touch-icon.png
  frontend/public/link-preview.png
  frontend/public/pwa-192x192.png
  frontend/public/pwa-512x512.png
Labels: please review

#1256 1170 Fix import for svg used in openstreetmap
  doc/changelog.md
  frontend/src/features/landing_page/components/GeoMap.tsx
Labels: please review

#1232 Improve documentation of schema.rs patch workflow.
  doc/backend/06updating_schema_patch.md
  doc/changelog.md
Labels: documentation, please review

#1227 Fix documentation issues
  doc/changelog.md
  doc/contrib/frontend.md
  doc/guidelines/frontend-api-calls.md
  doc/guidelines/frontend-locators.md
  doc/guidelines/i18n.md
  doc/meetings/2024_01_02.md
  doc/meetings/2024_01_08.md
  doc/meetings/2024_01_15.md
  doc/meetings/2024_01_22.md
  doc/meetings/2024_01_29.md
  doc/meetings/2024_02_05.md
  doc/meetings/2024_02_12.md
  doc/meetings/2024_02_19.md
  doc/research/nextcloud_integration.md
Labels: documentation

#1273 Fix/1249 plant label missing
  doc/changelog.md
  e2e/pages/inventory/create.py
  e2e/steps/test_inventory.py
  frontend/src/features/map_planning/layers/plant/PlantsLayer.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantLabel.tsx
  frontend/src/utils/plant-naming.test.tsx
  frontend/src/utils/plant-naming.tsx
Labels: please review, frontend, release critical

#1294 Add tests for hooks in frontend/layers
  doc/changelog.md
  frontend/src/__test_utils__/msw_handlers/plants.ts
  frontend/src/features/map_planning/layers/plant/hooks/relationsHookApi.test.tsx
  frontend/src/features/map_planning/layers/plant/hooks/useSelectPlantForPlanting.test.tsx
Labels: please merge

#1296 Add warn signs to attributeEditForm for multi-selected plant-areas
  doc/changelog.md
  frontend/src/features/map_planning/layers/plant/components/PlantLayerLeftToolbar.tsx
  frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
Labels: please review

#1332 Bug/1320 ci fails at mdbook job
  doc/Dockerfile
  doc/changelog.md
Labels: please review

#1291 feat(#1289): add points in middle of polygon
  doc/changelog.md
  frontend/src/config/i18n/de/drawings.json
  frontend/src/config/i18n/en/drawings.json
  frontend/src/features/map_planning/layers/drawing/DrawingAttributeEditForm.tsx
  frontend/src/features/map_planning/layers/drawing/DrawingLayer.tsx
  frontend/src/features/map_planning/layers/drawing/shapes/BezierPolygon.tsx
  frontend/src/features/map_planning/types/PolygonTypes.ts
  frontend/src/features/map_planning/utils/PolygonUtils.test.ts
  frontend/src/features/map_planning/utils/PolygonUtils.ts
Labels: please merge

#1263 962 refactor and test timeline
  doc/changelog.md
  frontend/src/features/map_planning/components/timeline/TimelineDatePicker.test.tsx
  frontend/src/features/map_planning/components/timeline/TimelineDatePicker.tsx
  frontend/src/features/map_planning/layers/plant/actions.ts
  frontend/src/features/map_planning/routes/MapWrapper.tsx
  frontend/src/features/map_planning/store/MapStoreTypes.ts
  frontend/src/features/map_planning/store/TimeLineStore.test.ts
  frontend/src/features/map_planning/store/TimeLineStore.ts
  frontend/src/features/map_planning/utils/TimelineEventsHelper.ts
Labels: please merge

#1319 1277 Left Toolbar Text cut off fix
  doc/changelog.md
  doc/guidelines/frontend-ui-usability.md
  frontend/src/features/map_planning/layers/plant/components/PlantingAttributeEditForm.tsx
Labels: please review
